spring.datasource.url=jdbc:postgresql://localhost:5432/product
spring.datasource.username=postgres
spring.datasource.password=1234567

api.security.token.secret=${JWT_SECRET:my-secret-key}

logging.level.root=INFO
logging.level.com.example=DEBUG
